main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("spectr.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

spectr/urls.py
from django.urls import path
from .views import  (
    index,
    category_detail,
    product_detail,
    contact_us,
     
)


app_name = 'spectr'


urlpatterns = [
    path('', index, name = "index" ),    
    path('category/<int:pk>/', category_detail, name = "category_detail" ),
    path('product/<int:pk>/', product_detail, name = "product_detail"),
    path('contact_us', contact_us, name = "contact_us"),
    ]

spectr/models.py
from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType


CREATED = "CREATED"
PENDING = "PENDING"
IN_WAY = "IN_WAY"
DONE = "DONE"

CART_CHOICES = (
    (CREATED, "Created"),
    (PENDING, "Pending"),
    (IN_WAY, "In way"),
    (DONE, "Done")
)

class Category(models.Model):
    name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=1200)
    description = models.TextField(max_length=1200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    count = models.IntegerField(default=0)
    sell = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

class Image(models.Model):
    photo = models.ImageField(upload_to='images')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")

class Order(models.Model):
    name = models.CharField(max_length=100)
    number = models.IntegerField()
    description = models.CharField(max_length=200)
    done = models.CharField(max_length=100)

class Carousel(models.Model):
    text = models.TextField(max_length=200)
    image = models.ImageField(upload_to='images')
    active = models.BooleanField(default=True)


# Create your models here.

spectr/forms.py
from django import forms

class CommentForm(forms.Form):
    your_name = forms.CharField(label='Ваше имя', max_length=100, required = True,widget = forms.TextInput(attrs = {
        'class': 'form-control',}))
    your_email = forms.EmailField(label='Ваш email', max_length=100, required = True,widget = forms.TextInput(attrs = {
        'class': 'form-control',}))
    your_message = forms.CharField(label='Ваше сообщение', max_length=300, required = True,widget = forms.Textarea(attrs = {
        'class': 'form-control',}))

spectr/views.py
import telegram

from django.conf import settings

from django.shortcuts import redirect, render
from django.contrib import admin
from .models import Category, Product, Order, Carousel
from .forms import CommentForm
from spectr import utils

def index(request):
    categorys = Category.objects.all()
    carousel = Carousel.objects.filter()
    return render(request, 'index.html', context = {"categorys":categorys, 'carousel': carousel})

def category_detail(request, pk):
    categorys = Category.objects.all()
    products = Product.objects.filter(category__id=pk)
    return render(request,'shop.html', context = {'products':products,"categorys":categorys})

def product_detail(request, pk):
    categorys = Category.objects.all()
    product = Product.objects.filter(id=pk).first()
    return render(request,'shop-detail.html', context={'product':product,"categorys":categorys})

def contact_us(request):
    categorys = Category.objects.all() 
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        dict = request.POST.copy()
        dict.pop("csrfmiddlewaretoken")
        message = utils.message.format(**dict)
        message = message.replace('[','')
        message = message.replace(']','')
        message = message.replace("'","")
        bot = telegram.Bot(token=settings.BOT_TOKEN)
        bot.send_message(chat_id=settings.CHAT_ID, text=message)
        return redirect('spectr:index')
    return render(request,'contact-us.html', context={"categorys":categorys,"form":form})

spectr/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>ThewayShop - Ecommerce Bootstrap 4 HTML Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
   a:link {
    color: #0000d0; /* Цвет ссылок */
    padding: 2px; /* Поля вокруг текста */ 
   }
   a:hover {
    background: #786b59; /* Цвет фона под ссылкой */ 
    color: #ffe; /* Цвет ссылки */ 
   } 
  </style>

</head>

<body>
                    
                    <div class="our-link">
                        <ul>
                            {% comment %} <li><a href="#">My Account</a></li> {% endcomment %}
                            {% comment %} <li><a href="#">Наше местоположение</a></li>
                            <li><a href="#">Связаться</a></li> {% endcomment %}
                    
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Main Top -->

    <!-- Start Main Top -->
    <header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                    <div id="greeting">
                        <a class="navbar-brand" href="index.html"><img id="headerImage" style="width:70px;" src="{% static 'images/thread.png' %}" class="logo" alt=""></a>
                        <h1 id="greetin-h1">SPECTR MASTER</h1>
                    </div>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                        <li class="nav-item active"><a class="nav-link" href="{% url "spectr:index" %}">Главное</a></li>
                        {% comment %} <li class="nav-item"><a class="nav-link" href="about.html">About Us</a></li> {% endcomment %}
                        <li class="dropdown megamenu-fw">
                            <a href="#" class="nav-link dropdown-toggle arrow" data-toggle="dropdown">Наши услуги</a>
                            <ul class="dropdown-menu megamenu-content" role="menu">
                                <li>
                                    <div style='width 300px;' class="row">
                                        <div style='width: 300px;'>
                                            <h6 style='padding-left:50px' class="title">Top</h6>
                                            <div style='padding-left:50px' class="content">
                                                <ul class="menu-col">
                                                    {% for category in categorys %}   
                                                        <p><a href="{% url 'spectr:category_detail' pk=category.id %}"><h1> {{category.name}} </h1></a></p>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                        
                                    </div>
                                    <!-- end row -->
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'spectr:contact_us' %}">Связаться с нами</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->

                <!-- Start Atribute Navigation -->
                {% comment %} <div class="attr-nav">
                    <ul>
                        <li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
                        <li class="side-menu"><a href="#">
						<i class="fa fa-shopping-bag"></i>
                            <span class="badge">3</span>
					</a></li>
                    </ul>
                </div> {% endcomment %}
                <!-- End Atribute Navigation -->
            </div>
            
        </nav>
        <!-- End Navigation -->
    </header>
    <!-- End Main Top -->


    {% block content %}


    {% endblock %}

  
    <!-- Start Footer  -->
    <footer>
        <div class="footer-main">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="footer-widget">
                            <h4>О нас</h4>
                            <p>Наши специалисты сделают для вас визуализацию будущих изделий в желаемом цвете и с брендированием. Вам же останется утвердить заказ в работу.
                                </p>
                            {% comment %} <ul>
                                <li><a href="https://t.me/SpectrMaster" target="_blank"><i class="fab fa-telegram-plane" aria-hidden="true"></i></a></li>
                                <li><a href="https://api.whatsapp.com/send? phone=+996553102424" target="_blank"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></li>
                            </ul> {% endcomment %}
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="footer-link">
                            <h4>ИНФОРМАЦИЯ</h4>
                            <ul>
                                {% comment %} <li><a href="#">Отзывы</a></li>
                                <li><a href="#">Актуальные вопросы</a></li> {% endcomment %}
                                <li><a href="#">Информация о доставке</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="footer-link-contact">
                            <h4>СВЯЗАТЬСЯ С НАМИ</h4>
                            <ul>
                                <li>
                                    <p><i class="fas fa-map-marker-alt"></i>Адрес: Кыргызстан, город Бишкек<br>улица Матросова,<br> 1А </p>
                                </li>
                                <li>
                                    <p><i class="fas fa-phone-square"></i>Телефон: <a href="tel:+996553102424">+996553102424</a></p>
                                </li>
                                <li>
                                    <p><i class="fas fa-envelope"></i>Email: <a href="mailto:ulanzhumagaziev@gmail.com">ulanzhumagaziev@gmail.com</a></p>
                                </li>
                                 <li>
                                    <p><a href="https://t.me/SpectrMaster" target="_blank"><i class="fab fa-telegram"></i>Telegram: SpectrMaster</a></p>
                                </li>
                                <li>
                                    <p><a href="https://api.whatsapp.com/send? phone=+996553102424" target="_blank"><i class="fab fa-whatsapp"></i>Whatsapp</a></p>
                                </li>
                            </ul>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer  -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

    <!-- ALL JS FILES -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'js/jquery.superslides.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/inewsticker.js' %}"></script>
    <script src="{% static 'js/bootsnav.js.' %}"></script>
    <script src="{% static 'js/images-loded.min.js' %}"></script>
    <script src="{% static 'js/isotope.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js ' %}"></script>
    <script src="{% static 'js/baguetteBox.min.js' %}"></script>
    <script src="{% static 'js/form-validator.min.js' %}"></script>
    <script src="{% static 'js/contact-form-script.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

spectr/templates/shop-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Start Top Search -->
    <div class="top-search">
        <div class="container">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                <input type="text" class="form-control" placeholder="Search">
                <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
            </div>
        </div>
    </div>
    <!-- End Top Search -->

    <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% comment %} <h2>Shop Detail</h2> {% endcomment %}
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Наши услуги</a></li>
                        {% comment %} <li class="breadcrumb-item active">Shop Detail </li> {% endcomment %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Shop Detail  -->
    <div class="shop-detail-box-main">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-6">
                    <div id="carousel-example-1" class="single-product-slider carousel slide" data-ride="carousel">
                        <div class="carousel-inner" role="listbox">

                            {% for i in product.images.all %}
                                {% if forloop.first %}
                                    <div class="carousel-item active">
                                {% else %}
                                    <div class="carousel-item">
                                {% endif %}
                                    <img class="d-block w-100" src="{{i.photo.url}}" alt="First slide"> </div>
                                {% comment %} {% elif i.photo.url %}
                                    div class="carousel-item"> <img class="d-block w-100" src="{{i.photo.url}}" alt="Other slide"> </div> {% endcomment %}
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carousel-example-1" role="button" data-slide="prev"> 
						<i class="fa fa-angle-left" aria-hidden="true"></i>
						<span class="sr-only">Previous</span> 
					</a>
                        <a class="carousel-control-next" href="#carousel-example-1" role="button" data-slide="next"> 
						<i class="fa fa-angle-right" aria-hidden="true"></i> 
						<span class="sr-only">Next</span> 
					</a>
                        <ol class="carousel-indicators">
                            {% for i in product.images.all %}
                                <li data-target="#carousel-example-1" data-slide-to="0" class="active">
                                    <img class="d-block w-100 img-fluid" src="{{i.photo.url}}" alt="" />
                                </li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>

                <div class="col-xl-7 col-lg-7 col-md-6">
                    <div class="single-product-details">
                        <h2>{{product.name}}</h2>
                        <h5> {{product.price}}</h5>
                        
                                <h4>Краткое описание:</h4>
                                <p>{{product.description}}</p>
                                

                    </div>
                </div>
            </div>

           <br>
            <br>
            <br>

    <!-- Start Instagram Feed  -->
    <div class="instagram-box">
        <div class="main-instagram owl-carousel owl-theme">
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-01.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-02.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-03.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-04.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-05.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-06.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-07.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-08.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-09.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ins-inner-box">
                    <img src="{% static 'images/instagram-img-05.jpg' %}" alt="" />
                    <div class="hov-in">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Instagram Feed  -->

{% endblock %}